### ISSUE TITLE
Lacks Hardware

### ISSUE THREAD

**Issue by visualecho1** [teafella/VidBoi#2]
It's a box with knobs on it.  What's inside?

**Comment by teafella** [comment]
Ah sorry yes this might be a bit vague since I’m still working on the hardware.

The pictured prototype is an Adafruit Metro Mini + Pi Zero on the inside.

I am currently working on a board design to make a pi hat that includes an ADC (MCP3008) and encorporates pcb mount jacks/ knobs so the Arduino is no longer necessary.

The Arduino is only there in the prototype because it was the fastest way to get analog inputs for me at the time.

I will make sure to post an update with details once that’s done in the next month or so.

**Comment by wraybowling** [comment]
@teafella Let's talk. This is something I've already started on with an almost identical project.

**Comment by teafella** [comment]
@wraybowling  sure yeah, shoot me an email: ronaldsardarian@gmail.com

**Comment by teafella** [comment]
Just an update on the hardware:
1st PCB for the V1 VidBoi (MCP 3008) is done, currently waiting on samples. 

Side Issue: Does anyone know a fast turn around PCB manufacturer that won't break the bank? ( for ordering to USA)

**Comment by visualecho1** [comment]
I recommend https://www.smart-prototyping.com/ .  I've used them a few dozen times, 0.15 (6 mil) trace/space, 0.3 (12 mil) smallest vias, like $5 for 10 count 25cm^2.  It's the $40 DHL from Hong Kong that's a bit steep, but you'll have blank PCBs on your doorstep in 10 days.

**Comment by teafella** [comment]
Ah nice, thanks for the tip I'll check them out!

Just got some boards from jlcpcb but yeah man that leadtime just might be worth it.

**Comment by teafella** [comment]
Added a version of the current working V1 PCB at /hardware. Its not perfect but, it works!
