### ISSUE TITLE
Does this build actually work?

### ISSUE THREAD

**Issue by johnbiehler** [teafella/VidBoi#3]
I read that you're working on a PCB and other things. I tried to make this build but it failed (missing wiring.h). 

Any chance to get it running to see what it looks like? I'm fine with using the arduino and everything on a breadboard.

**Comment by teafella** [comment]
Hey John,

This build is working, this file is from wiringpi:
wiringpi.com/download-and-install/

I have a prototype working on a metro mini where I hooked up 3pots and Jacks, you can look into the Arduino code to adjust it to your config if you're interested in doing that. It just sends strings over serial to communicate the analog readings.

I just ordered the first version of a vidboi board. I would prefer not to support Arduino based builds since there are too many moving parts to debug there.

**Comment by teafella** [comment]
Updated Readme to reflect that wiring pi needs to be installed

**Comment by johnbiehler** [comment]
Thanks for that! It was successfully built after installing WiringPI.

Can I launch it somehow without having to wire everything (Arduino/MCP/etc) just to see the HDMI output without any controls? 

Totally understand about supporting the arduino if you've moved to your own board (which I will anxiously await more details about).

I really love this idea and would like to integrate it into my eurorack.

**Comment by teafella** [comment]
No way to do this currently but I could add the option for keyboard control trivially I guess. Haven't run this in this way in a long time. I will try to add that as soon as I can move back to software things again.

Thanks! I'm glad you like it, Im realizing that powering this thing off a eurorack PSU will be a bit of a challenge but hopefully we will figure that out soon! (Could use help on that if you are any good at electronics) 

I will definitely update this repo with all board related things! (as soon as I know that they actually work haha)
