### ISSUE TITLE
Add Support for composite video output. 

### ISSUE THREAD

**Issue by CoolLeRue** [teafella/VidBoi#4]
Composite Video out would be super useful for those of us who work in SD. There might even be potential performance gains by dropping the resolution!

**Comment by teafella** [comment]
The rPI has a composite out on board so this should be trivial to do, would other people be interested in this? My only concern is that it will take up space on the resulting panel, the connector itself should be pretty cheap

**Comment by horizontalscale** [comment]
This would be very useful...

**Comment by teafella** [comment]
I have added composite out to the latest PCB, should be arriving in the mail next week. Composite is definitely in. Seems that HDMI is actually the bigger problem due to connector sourcing...

I will be looking for testers for that soon (especially since I work primarily in HD). Drop me a line if you're interested in doing this!

**Comment by CoolLeRue** [comment]
I'd be in to try to help with Composite testing! I've got a handful of CRTs, LCDs, and Projectors at my disposal.

**Comment by CoolLeRue** [comment]
Dang. I think I misunderstood you.
